// TMX-256 conformance — verified byte-for-byte against the frozen spec golden vectors
// (LogicN-R-AND-D/tmf/spec/tmx-256-construction-v0.md §10, generated by the Python stdlib
// reference gen_tmx_vectors.py). Matching these proves cross-language conformance.
import { test } from "node:test";
import assert from "node:assert/strict";
import { ABSENT, leafHash, nodeHash, topNode, tmxRoot } from "../dist/index.js";

const hex = (u) => Buffer.from(u).toString("hex");
const enc = new TextEncoder();
const le16 = (x) => { const b = new Uint8Array(2); new DataView(b.buffer).setUint16(0, x & 0xffff, true); return b; };
const le32 = (x) => { const b = new Uint8Array(4); new DataView(b.buffer).setUint32(0, x >>> 0, true); return b; };
const le64 = (x) => { const b = new Uint8Array(8); new DataView(b.buffer).setBigUint64(0, BigInt(x), true); return b; };
const cat = (...ps) => { const t = ps.reduce((n, p) => n + p.length, 0); const o = new Uint8Array(t); let k = 0; for (const p of ps) { o.set(p, k); k += p.length; } return o; };

const MAGIC = Uint8Array.from([0x89, 0x54, 0x4d, 0x46, 0x0d, 0x0a, 0x1a, 0x0a]);
const headerCore = (count) => cat(MAGIC, le16(0), le16(0), le16(0), le16(0), le64(count)); // [0..24)
const coord = (x, y, t) => cat(le32(x), le32(y), le32(t));                                  // i32le(x,y,t)

const leaf0 = leafHash(1, 0, coord(3, 5, 7), enc.encode("hello"));
const leaf1 = leafHash(1, 2, coord(3, 5, 8), enc.encode("world!"));

test("ABSENT sentinel matches the golden vector", () => {
  assert.equal(hex(ABSENT), "1758f20e501b1baaf42d5b2d5a07a9054e2134132139ae3d3af35f95f158d563");
});

test("leaf0 (kind=1, modality=0, coord=3,5,7, 'hello')", () => {
  assert.equal(hex(leaf0), "34eb47169cfaf5b3fac19670624c4dc4d7002838be5542625d6a90d2a5eefc72");
});

test("leaf1 (kind=1, modality=2, coord=3,5,8, 'world!')", () => {
  assert.equal(hex(leaf1), "65a4d5568838d568e1bfe45f96997b251674425a6243dc04da1ca548d211594b");
});

test("top_node = NODE(leaf0, leaf1, ABSENT)", () => {
  assert.equal(hex(topNode([leaf0, leaf1])), "0970038c1fe3b538db6f896672f560ceaf17cb8f0bdaf1fb53c8fe542667af0c");
  // and equals the explicit node construction
  assert.equal(hex(nodeHash(leaf0, leaf1, ABSENT)), hex(topNode([leaf0, leaf1])));
});

test("integrity_root binds header_core + top_node (2-section file)", () => {
  assert.equal(hex(tmxRoot(headerCore(2), [leaf0, leaf1])), "43386e644c7b53aa0900cda21c15acd15f30b3fdf997950e39e7dd3dbc685212");
});

test("single-leaf file: top is NODE(leaf0, ABSENT, ABSENT), never a bare leaf", () => {
  assert.equal(hex(topNode([leaf0])), "0ec91f7bf195b4954987aedacbfff3c188512c5fc1ff6d24db69cb95fc1e3c20");
  assert.notEqual(hex(topNode([leaf0])), hex(leaf0)); // a leaf is never reinterpretable as the top node
});

test("tamper detection: modality 0→1 on sec0 changes the root (fail-closed)", () => {
  const tampered = leafHash(1, 1, coord(3, 5, 7), enc.encode("hello"));
  assert.notEqual(
    hex(tmxRoot(headerCore(2), [tampered, leaf1])),
    "43386e644c7b53aa0900cda21c15acd15f30b3fdf997950e39e7dd3dbc685212",
  );
});

test("section order is bound: swapping sec0/sec1 changes the root", () => {
  assert.notEqual(hex(tmxRoot(headerCore(2), [leaf1, leaf0])), hex(tmxRoot(headerCore(2), [leaf0, leaf1])));
});

test("header_core is bound: a different section_count changes the root", () => {
  assert.notEqual(hex(tmxRoot(headerCore(3), [leaf0, leaf1])), hex(tmxRoot(headerCore(2), [leaf0, leaf1])));
});
